#+TITLE: Notes 2 - CC The Facts
#+AUTHOR: David Attenborough/Jack Maguire
#+DESCRIPTION: Notes


* Depressing

 - This has all happened before, but we are doing it too fast in comparison to nature
 - The faster we act, the better our chances are.
 - Changing because the world is hotter
 - There are dips and troughs, but here it's now nuts. Multiple sources agree.
 - When the changes first started, we didn't know what we were doing, but now we do.
 - No Natural Explanation - only one main explanation - the use of fossil fuels.
 - We're all using energy all the time, from fossil fuels.
 - WE USE THEM FOR EVERYTHING!
 - Before Coal, 280ppm of C02 in Atmos, but now its about 440ppm. 1 degree C. Not much, but a ton more in the grand scheme if things.
 - We can't say if climate change caused an event, but we can say if it made it more likely. Bcos of CC, we had a 30x chance of getting that.
 - Even creatures adapted to heat are dying out. Just not conceivable w/o CC. Over 11k flying foxes died last summer.
 - Not just about wonders of nature, we destabilise the world's ecosystems.
 - Lots of people lost their lives from fires.
 - Not just extreme weather, more rain as well. Super-storms and force-flooding events. Millions needed humanitarian aid.
 - The icecaps are melting. All melting is worse than expected. The water goes into the oceans, and we lose land by a football field every 45 mins. In the US, people are being offered $$$ to leave.
 - not only are oceans getting bigger, they're getting hotter
 - Took a while to work out what to do, for multiple reasons, including Big Fossil wanting to stay rich. Exact same PR agents as the Tobacco. Plus, Politicians don't want to do anything.
 - Problem is only getting harder to solve.
 - Trees hold carbon, but they are being destroyed and burnt which releases the carbon back...
 - Cleared and burnt, and replaced by Palms, Rubber Trees and pastures. Tons of Forest disturbance.
 - Prod of Food becomes more problematic.
 - Even at the better end, hundreds of millions are screwed. Even if the sea doesn't directly rise above them, the storms can get further than before.
 - Climate Tipping Points all around the world.
 - Lots of methane in the permafrost. As the permafrost becomes non-permanent frost, the methane comes up. Methane is 21x better as a greenhouse gas than CO2.

* Hopeful
 - We need to max out at 1.5, and half emissions by 2030, and null emissions by 2050.
 - One easier way is to change the power generation. Most countries have at least one natural resource to use.
 - Now, the stuff is getting cheaper, which makes everything else easier.
 - In the UK, we have been considering wind recently. We have *massive* offshore windfarms. We need to decarbonise industry and the transport centre. Hydrogen???
 - Do we incur a large cost now, or a *massive* cost later. We could even buy ourselves time if we start now to crack some tough nuts like aviation. We are seeing a reduction in battery weight tho.
 - Aviation-wise, we're workig well, but we still need lots of time.
