#+TITLE: BLM Reflection
#+AUTHOR: Jack Maguire

* No Justice, No Peace
Most modern justice systems are based on the reward and punishment. If we do something good, then we get to earn money, support a family and do all the things we want to do. If we do wrong, then we get punished, either by financial means (meaning we can't spend money to do the things we want), or it we get prison sentences. The system only works if everyone follows the rules, because if some people don't have to follow the rules, the system is unfair, and the majority who follow the laws feel that if some people don't have to suffer punishment, then they shouldn't have to follow it when given. For example, in KCS, if no-one was here to enforce the one-way system, no-one would follow it, because most feel that it impacts on them. Referring back to BLM, the BLM protesters feel that police aren't given appropriate punishment. Should I choose to murder the person who sits next to me, purely for no reason, and fully knowing I would kill him, then I would go to prison/juvenille detention. However, lots of police are given no punishment for their heinous acts.
